//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKart_ServerSide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card_Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Card_Request()
        {
            this.EmiCard_Documents = new HashSet<EmiCard_Documents>();
            this.Joining_Fee = new HashSet<Joining_Fee>();
        }
    
        public int Card_Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CardType { get; set; }
        public string BankName { get; set; }
        public string AccountNumber { get; set; }
        public string IFSC_Code { get; set; }
        public string AadhaarNumber { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<int> VerifiedBy { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmiCard_Documents> EmiCard_Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Joining_Fee> Joining_Fee { get; set; }
    }
}
