//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKart_ServerSide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COD_UPI_Orders
    {
        public int OrderId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> UserId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string PaymentType { get; set; }
        public string PaymentStatus { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
