//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKart_ServerSide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMI_Card
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMI_Card()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int EmiCardId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> PaymentMethodId { get; set; }
        public Nullable<int> ActivatedBy { get; set; }
        public string CardType { get; set; }
        public string CardNumber { get; set; }
        public Nullable<decimal> TotalLimit { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string CardImage { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Payment_Methods Payment_Methods { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
