//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKart_ServerSide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQ
    {
        public int FaqId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
