//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKart_ServerSide.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IKartEntities : DbContext
    {
        public IKartEntities()
            : base("name=IKartEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Card_Request> Card_Request { get; set; }
        public virtual DbSet<COD_UPI_Orders> COD_UPI_Orders { get; set; }
        public virtual DbSet<EMI_Card> EMI_Card { get; set; }
        public virtual DbSet<EmiCard_Documents> EmiCard_Documents { get; set; }
        public virtual DbSet<FAQ> FAQs { get; set; }
        public virtual DbSet<Installment_Payments> Installment_Payments { get; set; }
        public virtual DbSet<Joining_Fee> Joining_Fee { get; set; }
        public virtual DbSet<Monthly_EMI_Calc> Monthly_EMI_Calc { get; set; }
        public virtual DbSet<Order_Cancellations> Order_Cancellations { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Payment_Details> Payment_Details { get; set; }
        public virtual DbSet<Payment_Methods> Payment_Methods { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Penalty> Penalties { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Refund> Refunds { get; set; }
        public virtual DbSet<Return> Returns { get; set; }
        public virtual DbSet<Support_Tickets> Support_Tickets { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
    }
}
