//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKart_ServerSide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Installment_Payments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Installment_Payments()
        {
            this.Penalties = new HashSet<Penalty>();
        }
    
        public int InstallmentId { get; set; }
        public Nullable<int> EMI_Id { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<int> PaymentId { get; set; }
    
        public virtual Monthly_EMI_Calc Monthly_EMI_Calc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Penalty> Penalties { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
