//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKart_ServerSide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Joining_Fee
    {
        public int Fee_Id { get; set; }
        public Nullable<int> Card_Id { get; set; }
        public Nullable<int> PaymentMethodId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Status { get; set; }
        public string RazorpayPaymentId { get; set; }
        public string PaymentId { get; set; }
    
        public virtual Card_Request Card_Request { get; set; }
        public virtual Payment_Methods Payment_Methods { get; set; }
    }
}
