//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKart_ServerSide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monthly_EMI_Calc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Monthly_EMI_Calc()
        {
            this.Installment_Payments = new HashSet<Installment_Payments>();
        }
    
        public int EMI_Id { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> EMIAmount { get; set; }
        public Nullable<int> TenureMonths { get; set; }
        public Nullable<decimal> RemainingAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Installment_Payments> Installment_Payments { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual User User { get; set; }
    }
}
