//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKart_ServerSide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_Details
    {
        public int PaymentDetailsId { get; set; }
        public Nullable<int> PaymentMethodId { get; set; }
        public string CardNumber { get; set; }
        public string BankName { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string CVV { get; set; }
    
        public virtual Payment_Methods Payment_Methods { get; set; }
    }
}
