//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKart_ServerSide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penalty
    {
        public int PenaltyId { get; set; }
        public Nullable<int> InstallmentId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> Days_Overdue { get; set; }
        public Nullable<decimal> PenaltyPerDay { get; set; }
        public Nullable<decimal> PenaltyAmount { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        public virtual Installment_Payments Installment_Payments { get; set; }
        public virtual User User { get; set; }
    }
}
