//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKart_ServerSide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refund
    {
        public int RefundId { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Reason { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> RefundDate { get; set; }
    
        public virtual Payment Payment { get; set; }
    }
}
